### ISSUE TITLE
Seek to share

### ISSUE THREAD

**Issue by Yuanhp-jnu** [tasymons/photparty#2]
Hi, I'm a scholar from China, and I saw your paper: Superresolution Reconstruction of Severely Undersampled Point-spread Functions Using Point-source Stacking and  Deconvolution, very well written. It helps me a lot. But I want to know more about the details of this method and want to implement this method. Do you keep the code of the paper? If so, can you share it with me? Thank you very much!

**Comment by tasymons** [comment]
Hi! I'm not able to share this code at this time, but am happy to answer questions about the algorithm if that would be helpful.

**Comment by Yuanhp-jnu** [comment]
&nbsp; &nbsp; hi!Thank you very much for your reply.
&nbsp; &nbsp; I really have a question to ask you: The second step in IBP algorithm is to use the result of RLD algorithm PRLD as Ptrue to repeat the stacking procedure, and the fine grid is downsampled and upsampled by the previously used scale factors.&nbsp; Is the role of this step to fit the PRLD and the source image?
&nbsp; &nbsp; Looking forward to&nbsp; your reply!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tasymons/photparty"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月12日(星期四) 凌晨2:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tasymons/photparty] Seek to share (Issue #2)





 
Hi! I'm not able to share this code at this time, but am happy to answer questions about the algorithm if that would be helpful.
